### ISSUE TITLE
stripos cyrillic issues

### ISSUE THREAD

**Issue by stratoss** [2amigos/yii2-arrayquery-component#3]
Hi, stripos doesn't play well with non-US chars, like Russian for example. I had issues with the like statement, because:
`stripos("тЕст", "е")` returns false, while `mb_stripos("тЕст", "е")` returns 1 as it should.

Would it be possible to use mb_stripos instead?

Regards

**Comment by tonydspaniard** [comment]
@stratoss i'll do my best asap

**Comment by stratoss** [comment]
Its nice to see this repo is not dead :) Thanks.

**Comment by tonydspaniard** [comment]
@stratoss done
