### ISSUE TITLE
Support PHPunit 5

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-arrayquery-component#4]
Haven't tried it, but should also run on v5
https://github.com/2amigos/yii2-arrayquery-component/blob/master/composer.json#L32

**Comment by tonydspaniard** [comment]
i'll do asap. Thanks @schmunk42

**Comment by schmunk42** [comment]
It's not too critical. 
I had an issue with another package and thought this one was causing the problems, but it wasn't ;)

**Comment by tonydspaniard** [comment]
done
